### DISCUSSION TITLE
Unable to deploy a Kaoto integration

### DISCUSSION THREAD

**Discussion by timothydilbert** [KaotoIO/kaoto-ui#1413] [Q&A]
I am trying to run Kaoto on OpenShift. After trying just about everything I can think of, I am now stuck.

**Attempt 1**
I was able to successfully deploy the Kaoto Standalone container and the Camel K Operator on OpenShift. However, when I try to create a KamelBinding manually via copy & paste (i.e. Administrator > Installed Operators > Camel K Operator > Kamelet Binding > Create KameletBinding) it doesn't work. After a few events, I get a message saying:
```
Condition "Ready" is "Unknown" for KameletBinding mar8-camelk: Integration "mar8-camelk" does not have a readiness condition
```

**Attempt 2**
I've tried the same steps as above, but with a Red Hat Integration - Camel K operator. No different outcome.

**Attempt 3**
I've tried using the "Deploy" button within Kaoto Standalone, and that doesn't seem to do anything.

**Attempt 4**
I installed the "Kaoto Operator", then deployed the Kaoto UI/Backend via Kaoto Operator > Kaoto > Create Kaoto. But there is no option under that for KameletBinding and the UI appears dated. 

**Summary**
I'm completely lost as to what to do to get up and started with creating a timer job in YAML via Kaoto, and deploying it to OpenShift. Any help would be much appreciated.

**Comment by mmelko** [comment]
Hi @timothydilbert. To me this looks like your Camel-K install doesn't work properly:
```
(i.e. Administrator > Installed Operators > Camel K Operator > Kamelet Binding > Create KameletBinding) it doesn't work. 
```
are you able to deploy some integration using camel-k cli ? (e.g `kamel run SOME_INTEGRATION.yaml`) ?

**Reply by timothydilbert** [reply]
Hi @mmelko.

I don't have camel-k cli installed on my macOS laptop. I am only just getting started on Camel K, so please excuse me if this is a silly question, but is this a requirement?

**Reply by mmelko** [reply]
np, you mean a requirement for a running Kaoto or Camel-K ? :) but in any case it's not.

**Reply by timothydilbert** [reply]
Hi @mmelko 

Below is the error I receive when I attempt `kamel run DOWNLOADED_YAML_FROM_KAOTO.yaml`.
```
Error: json: cannot unmarshal object into Go value of type []v1.Flow
```

See YAML file below:
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mar8-camelk
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
      kind: Kamelet
    properties:
      period: '10000'
      message: hello
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
      kind: Kamelet
    properties:
      showHeaders: 'true'
```
