### ISSUE TITLE
Support jq for predicate/expression

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1080]
### Please describe the feature that you want to propose

We added backend camel-jq support for predicate/expression - https://github.com/KaotoIO/kaoto-backend/issues/136
Let UI support it as well.

##### transform expression
```yaml
- transform:
  jq: '.field3'
```

##### choice-when predicate
```yaml
- choice:
    when:
    - jq: '.destination == "NA"'
      steps:
        - setHeader:
            name: 'kafka.OVERRIDE_TOPIC'
            constant: "TOPIC.NA"
    - jq: '.destination == "EMEA"'
      steps:
        - setHeader:
            name: 'kafka.OVERRIDE_TOPIC'
            constant: "TOPIC.EMEA"
    - jq: '.destination == "LATAM"'
      steps:
        - setHeader:
            name: 'kafka.OVERRIDE_TOPIC'
            constant: "TOPIC.LATAM"
    - jq: '.destination == "APAC"'
      steps:
        - setHeader:
            name: 'kafka.OVERRIDE_TOPIC'
            constant: "TOPIC.APAC"
```
