### ISSUE TITLE
When uploading a file, if the kind is not matching, the content is wiped out

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1121]
### Describe the Bug

Kind is not adapted to uploaded files (also for edited files) and the content is wiped out without warning

### Steps to Reproduce the Bug or Issue

- Open Kaoto UI
- In the three vertical dots -> Settings, check the "Type" (by default "KameletBinding") then Cancel
- Click on the button to show the source
- Upload a file which is of kind integration, for instance:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: integration
spec:
  flows:
  - from:
      uri: activemq:null:queue
      steps:
      - aggregate: {}
      - to:
          uri: log:null
```
- The source code is showing this code but the canvas stays empty
- when closing and reopening source, the content is wiped out and replaced by an empty KameletBinding

### Screenshots or Videos

![wipedOutContent](https://user-images.githubusercontent.com/1105127/213114490-d53eab42-8d84-4c8c-9647-a0e70a409cbf.gif)

### Platform

- OS: Fedora
- Browser: Chrome
- Version: main
