### ISSUE TITLE
Canvas not re-rendered on step-extension save

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#1182]
### Describe the Bug

Deleting a branch from the step extension is not triggering the re-render in the canvas. 

If you close and open the source code editor, the code is updated.
If you interact with the canvas, the canvas removes the branch, so the info is there somewhere.

### Steps to Reproduce the Bug or Issue

1. Use https://github.com/KaotoIO/step-extension-repository/pull/12 with the following View Definition:
```
name: Config
id: step-extension-do-try-eip
type: step
url: http://localhost:3002/remoteEntry.js
scope: 'stepextensiondotryeip'
module: './DoCatch'
constraints: 
   -
      mandatory: true
      operation: CONTAINS_STEP_NAME
      parameter: do-try
```
2. Change settings to Kamelet DSL
3. Replace template with
```
template:
    from:
      uri: asterisk:null
      steps:
      - do-try:
          steps:
          - set-property:
              name: sdfasdf
              simple: ola ke ase
          do-catch:
          - exception:
            - asdfasdf
            on-when:
              simple: '{name=null, constant=null, simple=something, jq=null, representerProperties={simple=something}}'
            steps:
            - remove-header:
                name: ola ke ase
          do-finally:
            steps:
            - set-header:
                name: asdf
                simple: ola ke ase
```
4. The canvas should show 3 branches
5. Open the try-catch configuration tab
6. Remove the branch
7. Profit.

### Screenshots or Videos

![imagen](https://user-images.githubusercontent.com/726590/215080572-9fb5cc0d-51d0-420b-afe9-5e4aa760c17c.png)

### Platform

- OS: Linux
- Browser: Firefox
