### ISSUE TITLE
Branching: Unable to modify branch (delete/add steps) that's deeper than 1 level

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#1191]
### Describe the Bug

Unable to edit branches that are deeper than 1 level:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'branches')
    at Object.onMiniCatalogClickInsert [as handleSelectStep] (PlusButtonEdge.tsx?6848:38:1)
    at handleSelectStep (MiniCatalog.tsx?d345:60:1)
    at onClick (MiniCatalog.tsx?d345:66:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:4213:1)
    at invokeGuardedCallback (react-dom.development.js?61bb:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:4291:1)
    at executeDispatch (react-dom.development.js?61bb:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js?61bb:9073:1)
    at processDispatchQueue (react-dom.development.js?61bb:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js?61bb:9097:1)
    at eval (react-dom.development.js?61bb:9288:1)
    at batchedUpdates$1 (react-dom.development.js?61bb:26140:1)
    at batchedUpdates (react-dom.development.js?61bb:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?61bb:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js?61bb:6465:1)
    at dispatchEvent (react-dom.development.js?61bb:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js?61bb:6430:1)
react-dom.development.js?61bb:4312 Uncaught TypeError: Cannot read properties of undefined (reading 'branches')
    at Object.onMiniCatalogClickInsert [as handleSelectStep] (PlusButtonEdge.tsx?6848:38:1)
    at handleSelectStep (MiniCatalog.tsx?d345:60:1)
    at onClick (MiniCatalog.tsx?d345:66:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:4213:1)
    at invokeGuardedCallback (react-dom.development.js?61bb:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:4291:1)
    at executeDispatch (react-dom.development.js?61bb:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js?61bb:9073:1)
    at processDispatchQueue (react-dom.development.js?61bb:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js?61bb:9097:1)
    at eval (react-dom.development.js?61bb:9288:1)
    at batchedUpdates$1 (react-dom.development.js?61bb:26140:1)
    at batchedUpdates (react-dom.development.js?61bb:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?61bb:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js?61bb:6465:1)
    at dispatchEvent (react-dom.development.js?61bb:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js?61bb:6430:1)
```

### Steps to Reproduce the Bug or Issue

1. Use this test kamelet: 
 ```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps:
          - delay:
              expression:
                simple: ${body}
              async-delayed: true
      - filter:
          simple: '{{?foo}}'
          steps:
          - to:
              uri: amqp:null:queue
          - circuit-breaker:
              description:
                text: Another one
                lang: eng
              steps:
              - enrich:
                  expression:
                    simple: ${body}
              - to:
                  uri: dropbox:put
                  parameters:
                    accessToken: '{{accessToken}}'
              - convert-body-to:
                  type: java.lang.String
                  charset: UTF8
              on-fallback:
                steps:
                - log:
                    message: test
                    logging-level: INFO
                    log-name: yaml
      - to:
          uri: kamelet:sink
```
2. try to delete / add step in Circuit breaker's branches

### Platform

MacOS: Chrome
