### ISSUE TITLE
Broken nested branches 

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#1255]
### Describe the Bug

When new branch is added inside of existing branch with a component A, the component A become disconnected and nested branch is connected to the parent of parent branch: 
![Kapture 2023-02-14 at 15 09 38](https://user-images.githubusercontent.com/6814482/218764108-7f483037-00e6-4ff4-b373-3036f3c56d60.gif)

### Steps to Reproduce the Bug or Issue

Use this integration as a starting point:
```yaml 
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: integration
spec:
  flows:
  - from:
      uri: timer:null
      steps:
      - choice:
          when:
          - simple: when
            steps:
            - log: {}
          otherwise:
            steps:
            - to:
                uri: log:null
      - log: {}
```
2. add Choice before one of the logs within a branch
3. add a new branch

### Platform

everywhere
