### ISSUE TITLE
Branching: Delete branch button not showing for empty & single-step branches

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1277]
### Describe the Bug

There is no way to delete branches that only contain a single step or that are empty with a placeholder. This is likely a regression.

It's unclear if it's simply a matter of the button being hidden (since there is not much space, see #1146), but it's likely that the delete button is simply not rendering for that type of edge. There is a function dedicated to building single-step edges, called `buildBranchSingleStepEdges`, so this is likely where the bug is.

### Steps to Reproduce the Bug or Issue

1. Open source code editor
2. Paste the following YAML into it
3. Press "Sync your code"
4. See empty branches or single-step branches (`filter` and `loop` for the YAML below)

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps: []
      - choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - to:
                uri: digitalocean:null
                parameters:
                  resource: '{}'
            - set-header:
                name: bar
                simple: foo
          - simple: '{{?bar}}'
            steps:
            - delay: {}
            - marshal:
                json:
                  library: Gson
          otherwise:
            steps:
            - pipeline: {}
            - claim-check:
                operation: Push
                key: foo
                filter: header:(foo|bar)
      - filter:
          simple: '{{?foo}}'
          steps: []
      - to:
          uri: kamelet:sink
```

### Screenshots or Videos

![Screen Shot 2023-02-17 at 12 54 04 pm](https://user-images.githubusercontent.com/3844502/219658549-e1a6d4a3-3a6c-4018-9355-baa28cb709b2.png)

### Platform

- OS: macOS, Linux
- Browser: Chrome
- Version: `0.6.2-dev`

Likely everywhere..
