### ISSUE TITLE
Branching: Delete branch button sometimes is covered

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1281]
### Describe the Bug

Sometimes you cannot delete a branch because the delete button is covered.

### Steps to Reproduce the Bug or Issue

1. Open the source code editor
2. Paste the following YAML
3. Press the save button
4. See the bottom-most branch and try to delete it, but the delete button is covered

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps:
          - delay:
              expression:
                simple: ${body}
              async-delayed: true
      - choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - to:
                uri: digitalocean:null
            - set-header:
                name: bar
                simple: foo
          - simple: '{{?bar}}'
            steps:
            - delay: {}
            - marshal:
                json:
                  library: Gson
          - simple: '{{?baz}}'
            steps:
            - choice:
                when: []
            - log:
                message: test
                logging-level: INFO
                log-name: yaml
          otherwise:
            steps: []
      - filter:
          simple: '{{?foo}}'
          steps: []
      - to:
          uri: kamelet:sink
```

### Screenshots or Videos

![screenshot-localhost_1337-2023 02 17-15_25_56](https://user-images.githubusercontent.com/3844502/219696282-bd3abd0b-64b0-4e08-9590-38f3c5e7a5a6.png)

### Platform

- OS: macOS, Linux
- Browser: Chrome
- Version: `0.6.2-dev`
