### ISSUE TITLE
E2E tests for critical user journeys

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1297]
### Please describe the task that needs to be done

We can use E2E tests to test individual components visually as well as to test user journeys (traditional E2E).

For this task, we don't need to test the presence or appearance of individual components as much as the user journey behaviors/actions, and that the user sees what is expected after those actions. If possible, it would be nice to test that the edges and nodes also don't disappear after certain actions. 😂  (example bug: https://github.com/KaotoIO/kaoto-ui/issues/1288)

![Nodes and Edges](https://user-images.githubusercontent.com/3844502/220414598-7a6210fc-a2de-4d51-857c-2c9dcd7306e1.png)

# Scenarios
User journeys with each visual component, some testing a "bad" behavior (invalid) to see if user sees proper validation.

\* = lower priority issue

## Catalog actions
- [ ] User drags and drops an invalid step onto a nested branch step (i.e. a `start` step when branches should start with `action` steps)
- [ ] User replaces a placeholder step via drag & drop from the big catalog
- [ ] User replaces a placeholder step using the mini catalog*

## Code editor actions
- [ ] User adds, edits, and removes a step from the YAML*
- [ ] User adds and removes a branch from the YAML
- [ ] User undoes a change they saved, syncs with canvas*
- [ ] User clears the state of the code editor, syncs with canvas*
- [ ] User uploads YAML file, syncs with canvas
- [ ] User downloads YAML file, syncs with canvas

## Step actions from the canvas
- [ ] User inserts a step between two steps (+ button in between two nodes)
- [ ] In an integration with at least two steps, user deletes the first step, showing a placeholder step in its place
- [ ] User appends a step (+ button to the right of the node)
- [ ] User prepends a step (+ button to the left of the node)
- [ ] Step Detail - User configures a normal step, which updates the YAML
- [ ] Step Extensions
  - [ ] User sees a step extension (e.g. `choice` step)
  - [ ] User configures a step from a step extension
  - [ ] User adds and removes a branch from a step using a step extension

## Branching actions from the canvas
- [ ] User adds a branch from the canvas
- [ ] User deletes a branch from the canvas
- [ ] User completes normal actions on steps in a branch (configure, delete, replace, add)
- [ ] User appends a step in a branch (+ button to the right of the node, usually for the last step in a branch)
- [ ] User prepends a step in a branch (+ button to the left of the node, usually for the first step in a branch)
- [ ] User prepends a step to a step whose previous step contains branches
- [ ] User adds a nested branch from the canvas
- [ ] User deletes a nested branch from the canvas
- [ ] User completes normal actions on steps in a nested branch (configure, delete, replace, add)

----

### YAML
If you are wanting to test nested branches, you can use the following YAML or any variation of it in the code editor where it makes sense (for example, if not testing building the branching visually and you want to save time):

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps:
          - delay:
              expression:
                simple: ${body}
              async-delayed: true
      - choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - to:
                uri: digitalocean:null
            - set-header:
                name: bar
                simple: foo
          - simple: '{{?bar}}'
            steps:
            - delay: {}
            - marshal:
                json:
                  library: Gson
          - simple: '{{?baz}}'
            steps:
            - choice:
                when: []
            - log:
                message: test
                logging-level: INFO
                log-name: yaml
          otherwise:
            steps:
            - pipeline:
                steps:
                - aggregate: {}
      - filter:
          simple: '{{?foo}}'
          steps: []
      - to:
          uri: kamelet:sink
```

Relates to #1099
