### ISSUE TITLE
Branching messed up with 3 branches with one having 2 steps

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1374]
### Describe the Bug

Branching messed up with 3 branches with one having 2 steps

for instance using this route:

```
- from:
    uri: timer:null
    steps:
    - choice:
        when:
        - simple: path1
          steps:
          - to:
              uri: https:null
        - simple: path2
          steps:
          - log: {}
        - simple: path3
          steps:
          - to:
              uri: avro:null:null:null:null
          - log: {}
        otherwise:
          steps:
          - log: {}
    - log: {}
```

### Steps to Reproduce the Bug or Issue

1. add a step
2. add a choice
3. add 3 branches
4. add 2 steps on one of the branches

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/222700120-478db3aa-d8cd-4c84-9d8e-76fd568e6176.png)

![messedUpbranch](https://user-images.githubusercontent.com/1105127/222700925-92680b64-8646-4ae5-a6c0-54fcee3913c2.gif)

### Platform

OperateFirst
