### ISSUE TITLE
Adding new branch using the "Add a branch" popover not reflected in the code editor

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1381]
### Describe the Bug

When user adds new branch for the Choice step using the "Add a branch" popover -   it adds a otherwise step:
```
otherwise:
      steps: []
```
This "otherwise" step can be added multiple times. Also the new branch is not reflected in the code editor.

### Steps to Reproduce the Bug or Issue

1. Add a branch to choice step using the "Add a branch" popover
2. It's not visible in the editor

### Screenshots or Videos

![Peek 2023-03-03 14-43](https://user-images.githubusercontent.com/4180208/222737007-2765a949-82ab-41ae-9751-27a6ab6c15e7.gif)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [latest]

**Comment by kahboom** [comment]
Uh oh that's not good..

**Comment by kahboom** [comment]
On hold due to https://github.com/KaotoIO/kaoto-backend/issues/512

**Comment by lordrip** [comment]
I was looking into this issue, so given that it was blocked by [another issue](https://github.com/KaotoIO/kaoto-backend/issues/512), I put together this [draft pull request](https://github.com/KaotoIO/kaoto-backend/pull/518) to discuss what to do in those cases

**Comment by lordrip** [comment]
now that the previous pull request it's merged, this issue is no longer on hold 🚀

**Comment by lordrip** [comment]
@Delawen I pretty-please summon your wisdom here :)

Let's consider the following case:

1. I start with a `kamelet:source` step, so we send this indivisual step to the backend to receive the coerresponding `yaml`
2. Then we add a `choice` step and we send now to the backend 2 steps and with this last step `{ branches: null }`
```
{
  dsl: "Camel Route"
  metadata: {
    description: ""
    dsl: { ... }
  },
  steps: [
    { ... kamelet:source ... },
    {
      branches: null
      id: "choice-MIDDLE"
      kind: "EIP-BRANCH"
      maxBranches: -1
      minBranches: 1
      name: "choice"
    }
  ]
}
```
3. We receive back:
```yaml
- from:
    uri: kamelet:source
    steps:
    - choice:
        when: [] # <--- this seems automatically generated
```
4. After that, we add a new branch and then we send to the backend the same payload but now including the newly added branch:
```
branchUuid: "b-1-670523182"
identifier: ""
steps: []
```
5. The response is:
```yaml
- from:
    uri: kamelet:source
    steps:
    - choice:
        when: []
        otherwise: # <--- :eyes: how this otherwise came here?
          steps: []
```

Now the question is, is this the right behavior or are we missing some information that we should send to the backend to properly attach branches with their UI counterpart :thinking: ?
