### ISSUE TITLE
Step tooltip sometimes empty

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1398]
### Describe the Bug

The [tooltip provider](https://github.com/KaotoIO/kaoto-ui/blob/main/src/services/validationService.ts#L111) (`getPlusButtonTooltipMsg`) is sometimes returning only a string by default, which shows as an empty tooltip. It's not clear when this is happening, but I noticed it happening for the button to prepend a step, on a step _after_ a step with branching.

We should be sure to catch any situation where this happens, and maybe not show the tooltip at all if there is no helpful message.

### Steps to Reproduce the Bug or Issue

1. Paste the YAML below into the source code editor
2. Hover over the `filter` prepend button
3. See empty tooltip

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
    - camel:core
    - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
        - loop:
            constant: "3"
            copy: true
            steps:
              - delay:
                  expression:
                    simple: ${body}
                  async-delayed: true
        - choice:
            when:
              - simple: "{{?foo}}"
                steps:
                  - to:
                      uri: digitalocean:null
                  - set-header:
                      name: bar
                      simple: foo
              - simple: "{{?bar}}"
                steps:
                  - delay: {}
                  - marshal:
                      json:
                        library: Gson
              - simple: "{{?baz}}"
                steps:
                  - choice:
                      when: []
                  - log:
                      message: test
                      logging-level: INFO
                      log-name: yaml
            otherwise:
              steps:
                - pipeline:
                    steps:
                      - aggregate: {}
        - filter:
            simple: "{{?foo}}"
            steps: []
        - to:
            uri: kamelet:sink

```

### Screenshots or Videos

![Screen Shot 2023-03-06 at 2 20 20 pm](https://user-images.githubusercontent.com/3844502/223136350-3feff7ff-d073-445e-8846-7b07f56d73dc.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.7.2-dev
