### ISSUE TITLE
Code editor highlights YAML as invalid when DSL doesn't match Settings

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1445]
### Describe the Bug

Pasting valid YAML of a different DSL than the one in Settings causes it to be highlighted until you close and reopen the code editor.

### Steps to Reproduce the Bug or Issue

1. Paste the following YAML into the code editor

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  - camel:amqp
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps:
          - delay:
              expression:
                simple: ${body}
              async-delayed: true
      - choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - to:
                uri: digitalocean:null
            - set-header:
                name: bar
                simple: foo
          - simple: '{{?bar}}'
            steps:
            - delay: {}
            - marshal:
                json:
                  library: Gson
          otherwise:
            steps:
            - pipeline:
                steps: []
      - to:
          uri: amqp:null:queue
      - aggregate: {}
      - filter:
          simple: '{{?foo}}'
          steps: []
      - to:
          uri: kamelet:sink
```

2. Close and open Code Editor, see the highlighting goes away

### Screenshots or Videos

![Screen Shot 2023-03-10 at 10 29 50 am](https://user-images.githubusercontent.com/3844502/224293866-aa18380f-eb53-4156-9177-e38380b7889c.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
