### ISSUE TITLE
DSL is not automatically updated in Settings

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1446]
### Describe the Bug

When pasting valid YAML with a different DSL to the one in Settings, the DSL is not being updated in Settings.

### Steps to Reproduce the Bug or Issue

1. Paste the following YAML into the code editor
2. Press sync button

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
  - camel:core
  - camel:kamelet
  - camel:amqp
  template:
    from:
      uri: kamelet:source
      steps:
      - loop:
          constant: '3'
          copy: true
          steps:
          - delay:
              expression:
                simple: ${body}
              async-delayed: true
      - choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - to:
                uri: digitalocean:null
            - set-header:
                name: bar
                simple: foo
          - simple: '{{?bar}}'
            steps:
            - delay: {}
            - marshal:
                json:
                  library: Gson
          otherwise:
            steps:
            - pipeline:
                steps: []
      - to:
          uri: amqp:null:queue
      - aggregate: {}
      - filter:
          simple: '{{?foo}}'
          steps: []
      - to:
          uri: kamelet:sink

```

### Screenshots or Videos

![Kapture 2023-03-10 at 10 57 34-02](https://user-images.githubusercontent.com/3844502/224301003-82d22ca1-332a-46ea-a579-baf0d911ec24.gif)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
