### ISSUE TITLE
Syncing the code loses the currently selected step if said step is nested

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1475]
### Describe the Bug

Having selected a nested step, if the code is synced, this value gets lost. This might be caused by how the IDs are calculated [from this line](https://github.com/KaotoIO/kaoto-ui/blob/main/src/services/stepsService.ts#L470)

```typescript
if (branchSteps) step.UUID = `${step.name}-${idx}-${getRandomArbitraryNumber()}`;
```

### Steps to Reproduce the Bug or Issue

1. Use the following `yaml` file as a starting point
```yaml
- from:
    uri: as2:null:null
    steps:
    - choice:
        when:
        - simple: 'This is a simple condition'
          steps: []
        otherwise:
          steps:
          - choice:
              when:
              - jq: 'This is a nested JQ condition'
                steps: []
```

2. Click on the nested `choice` step
3. Sync the code
4. Notice how the selected step gets lost and the view is not right

### Screenshots or Videos

[Screencast from 2023-03-14 14-16-48.webm](https://user-images.githubusercontent.com/16512618/225012806-0ab4ae3e-f3b1-45ac-bcf0-e9cd1ff43cd0.webm)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.2-dev]
