### ISSUE TITLE
[Epic] Support expression dialect

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1506]
### Describe the Bug

We support
```yaml
- from:
    uri: timer:null
    steps:
    - set-body:
        simple: test
```

but not
```yaml
- from:
    uri: timer:null
    steps:
    - set-body:
        expression:
          simple:
            expression: test
```

Both needs to be supported as a dialect. Canvas should show same diagram on both route above.
There're several EIPs uses expression, some of them has its step extension, but the others don't. Both of default Config tab and step extensions should make a fix for this.

#### Related Issues
- https://github.com/KaotoIO/kaoto-backend/issues/479
- https://github.com/KaotoIO/kaoto-backend/issues/547
- https://github.com/KaotoIO/kaoto-backend/issues/548

### Steps to Reproduce the Bug or Issue

1. Open source code editor
2. Paste the 2nd YAML above

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by igarashitm** [comment]
We might be able to keep `expression` object as-is in default config tab, with "disabled"-ish style and suggest user to configure in source code editor. but definitely not lose the data.

**Comment by igarashitm** [comment]
The other option for post 1.0 is to align to the one of dialects we choose, and always convert into the chosen one. IMO it's not necessary to preserve the source code in a dialect user choose, as long as it's semantically preserved. If user wants to keep the source code at that level, they should use the code editor alone. Or we can add `hardcore source editing mode` which disables the canvas completely.

**Comment by Delawen** [comment]
I am all for converting identical code into a single coding style. Consistency pushing the user into what are best practices.

**Comment by igarashitm** [comment]
This seems to be an another dialect to support
```yaml
- from:
    uri: timer:null
    steps:
    - set-body:
        simple:
          expression: test
          resultType: String
```

And enforcing `resultType` seems **NOT** to be supported with the simplest dialect (1st in the description). So if we go to the auto-converting route, we should choose one of the verbose styles.
https://stackoverflow.com/questions/75003733/apache-camel-yaml-dsl-expression-returning-custom-datatype
