### ISSUE TITLE
Wrong display of route with a component log as middle step (first example of Camel Yaml route in official Camel documentation)

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1562]
### Describe the Bug

The example of Yaml route in official Camel documentation is not rendered correctly. https://camel.netlify.app/camel-k/latest/languages/yaml.html#_defining_a_route

### Steps to Reproduce the Bug or Issue

1. Open source code editor
2. Paste
```


- from: 
    uri: "direct:start"
    steps: 
      - filter:
          expression:
            simple: "${in.header.continue} == true"
          steps: 
            - to:
                uri: "log:filtered"
      - to:
          uri: "log:original"


```
3. Click `Sync code` button
--> a log is displayed on a second line

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/227964572-676bffbf-6dc8-4dcb-96d0-8c4cc620f212.png)

### Platform

- OS: Fedora
- Browser:VS Code
- Version: 0.7.5
