### ISSUE TITLE
Cannot load route from Red Hat Quarkus superHeroes example

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1564]
### Describe the Bug

Using route defined here https://github.com/pprosser-redhat/quarkus-super-heroes/blob/c530dd797f0ab35e50a0c07e6cf7cb4ab7c75a14/camelkfordebezium/crudlegacyheroes.camel.yaml#L3

```yaml
- from:
      uri: kamelet:kafka-source
      id: from-4592
      parameters:
        bootstrapServers: my-cluster-kafka-bootstrap.superheroes.svc:9092
        topic: philsmac.phil.hero
        user: test
        password: test
        securityProtocol: PLAINTEXT
        consumerGroup: customers4
        autoCommitEnable: true
        autoOffsetReset: earliest
      steps:
        - log:
            message: '"Boom, a message ${body}"'
            id: log-9b74
            loggingLevel: INFO
        - choice:
            when:
              - id: when-6f94
                expression:
                  simple:
                    expression: ${body} != null
                    id: simple-6ea9
                steps:
                  - setHeader:
                      name: operation
                      id: setHeader-64d1
                      expression:
                        jsonpath:
                          expression: $.payload.op
                          id: jsonpath-dc29
                      description: get operation value
                  - setHeader:
                      name: snapshot
                      id: setHeader-1145
                      expression:
                        jsonpath:
                          expression: $.payload.source.snapshot
                          id: jsonpath-4564
                      description: get snapshot value
                  - to:
                      uri: direct:WorkOutWhatToDo
                      id: to-88d9
                      description: How do I talk to the DB
                  - log:
                      message: done
                      id: log-0068
                  - choice:
                      when:
                        - id: when-c579
                          expression:
                            simple:
                              expression: ${header.operation} == 'u'
                              id: simple-ae94
                          description: Update Hero
                          steps:
                            - to:
                                uri: kamelet:postgresql-sink
                                id: to-97da
                                parameters:
                                  query: >-
                                    UPDATE hero SET level = :#level, name =
                                    :#name, othername = :#othername, picture =
                                    :#picture, powers = :#powers  WHERE id =
                                    :#id
                                  databaseName: heroes_database
                                  serverName: heroes-db.default.svc.cluster.local
                                  serverPort: 5432
                                  username: superman
                                  password: superman
                                description: update DB
                        - id: when-6bc7
                          expression:
                            simple:
                              expression: ${header.operation} == 'c'
                              id: simple-8a4b
                          description: Create a new Hero
                          steps:
                            - to:
                                uri: kamelet:postgresql-sink
                                id: to-198b
                                parameters:
                                  query: >-
                                    INSERT INTO hero (id, level, name,
                                    othername, picture, powers) VALUES (:#id,
                                    :#level, :#name, :#othername, :#picture,
                                    :#powers)
                                  databaseName: heroes_database
                                  serverName: heroes-db.default.svc.cluster.local
                                  serverPort: 5432
                                  username: superman
                                  password: superman
                                  description: Insert DB
                                description: Insert DB
                        - id: when-24b0
                          expression:
                            simple:
                              expression: ${header.operation} == 'd'
                              id: simple-c4d6
                          description: Delete a Hero
                          steps:
                            - to:
                                uri: kamelet:postgresql-sink
                                id: to-522f
                                parameters:
                                  query: DELETE FROM hero WHERE id=:#id
                                  databaseName: heroes_database
                                  serverName: heroes-db.default.svc.cluster.local
                                  serverPort: '5432'
                                  username: superman
                                  password: superman
                                description: Delete DB
                      id: choice-40b3
            id: choice-f747
            otherwise:
              id: otherwise-41f6
              steps:
                - log:
                    message: no message to process
                    id: log-e37a
                    description: no message to process
```

it cannot be loaded

in console log:
```
VM475 react_devtools_backend.js:2655 TypeError: Cannot read properties of null (reading 'name')
    at stepsService.ts:466:27
    at Array.forEach (<anonymous>)
    at StepsService.regenerateUuids (stepsService.ts:465:14)
    at stepsService.ts:471:47
    at Array.forEach (<anonymous>)
    at stepsService.ts:469:24
    at Array.forEach (<anonymous>)
    at StepsService.regenerateUuids (stepsService.ts:465:14)
    at stepsService.ts:471:47
    at Array.forEach (<anonymous>)
```

### Steps to Reproduce the Bug or Issue

1. Open source code editor
2. Paste route provided above
3. Click `sync code`
4. --> nothing is loaded

### Platform

OperateFirst
