### ISSUE TITLE
UI is not handling `END` branch steps

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1587]
### Describe the Bug

The frontend is not handling steps within a branch that are `END` steps (such as `stop`), and if you add one via YAML it causes the integration to break (see screenshots).

We currently treat steps that are available as either `MIDDLE` or `END` steps as `MIDDLE` steps, but sometimes we have steps that are only available as `END` steps. At the moment, there is only one example of such a step, and that's the `stop` step.

Right now, we are changing the `stop` step to be a `MIDDLE` step so as to not break the UI, but eventually we will need to handle these step types as `END` steps, to provide a better UX on the frontend. For example, if a branch that has a `stop` step should not have anything after it unless there is some other execution flow available (i.e. another branch).

Relates to https://github.com/KaotoIO/kaoto-ui/issues/1562 and https://github.com/KaotoIO/kaoto-backend/issues/586

### Steps to Reproduce the Bug or Issue

Paste the following YAML into the source code editor.

```yaml
- from:
    uri: activemq:queue:null
    steps:
    - choice:
        when:
        - steps:
          - to:
              uri: activemq:queue:null
          - stop: {}
        - steps: []
        - steps: []
    - to:
        uri: avro:null:null:null/null
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/726590/228228543-9080267a-68dc-41f0-81ed-4af0c504be86.png)

![image](https://user-images.githubusercontent.com/726590/228229031-603a8404-c46e-4daf-95c8-6ef507aaeaac.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
