### ISSUE TITLE
Required object parameters gets removed from the Code Editor when opening Step Details

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1603]
### Describe the Bug

Having a step with a required object type parameter gets removed from the Code Editor.

The same happens if the same parameter is specified in the code editor and later edited in the Step's details panel.

### Steps to Reproduce the Bug or Issue

1. Starting with a blank canvas, paste the following `YAML`
```yaml
- from:
    uri: timer:my-timer
    parameters:
      period: # Period it's a `duration` paramater but the UI receives it as `object`
        dummy-property:
          nested-property: 10
    steps:
    - marshal:
        json:
          library: Gson
```
2. Sync the code
3. Click on `marshal` to open the step's details
4. Notice how now the `JSON` property gets removed
5. Close the step's details panel
6. Click on the timer
7. Notice how the period parameter is not removed from the code editor since it's not a required property.

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.6-dev]
