### ISSUE TITLE
Route is not displayed correctly

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1628]
### Describe the Bug

When copy & paste the route at https://pastebin.com/raw/5GjkzGfN to the code editor the displayed route on the canvas is not correct and the code is partially getting discarded. See picture.

![grafik](https://user-images.githubusercontent.com/435853/230040755-63e7e481-f6f3-4572-8b69-03e3d608cc51.png)

### Steps to Reproduce the Bug or Issue

1. copy & paste the code from https://pastebin.com/raw/5GjkzGfN to the Kaoto internal editor and hit "Apply"
2. see the result in both editor and graphical view
3. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by apupier** [comment]
reproducing with a simpler route (which can still be surely simplified):

```
- from:
    uri: timer:trigger-gitter-streaming
    parameters:
      repeatCount: 1
    steps:
    - loop:
        expression:
          simple: {}
        do-while: true
        steps:
        - choice:
            when:
            - expression:
                jsonpath: {}
              steps:
              - wire-tap:
                  uri: kamelet:sink
              - set-body:
                  expression:
                    simple: {}
```
