### ISSUE TITLE
Add a name to a flow

### ISSUE THREAD

**Issue by skin27** [KaotoIO/kaoto-ui#1711]
### Please describe the feature that you want to propose

Currently,  a flow in Kaoto doesn't have name. It would be nice if the flow has a name by default.

Current generated code (Camel YAML DSL):

```
- from:
    uri: file:C:\messages\in
    steps:
    - to:
        uri: log:MyLogger
    - to:
        uri: file:C:\messages\out
```

This could be:

```
- route:
    id: route-0d88
    from:
      uri: file:C:\messages\in
      steps:
      - to:
          uri: log:MyLogger
      - to:
          uri: file:C:\messages\out

```

The user may give it a name (in the gui), but it can be generated (similar to karavan). The format is then also the same as karavan.  

This can also help in the future when using it as an integration. Because then you can manage integrations with muliple flows:
```

apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: myintegration
spec:
  flows:
  - route:
	  id: route-1
	  from:
	    uri: file:C:\messages\in
	    steps:
	    - to:
		    uri: log:MyLogger
	    - to:
		    uri: file:C:\messages\out
  - route:
	  id: route-1
	  from:
	    uri: file:C:\messages\in2
	    steps:
	    - to:
		    uri: log:MyLogger2
	    - to:
		    uri: file:C:\messages\out2
```
