### ISSUE TITLE
Add Beans support

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1721]
### Please describe the feature that you want to propose

Support loading this YAML route. Currently it's wiped out when sync button is clicked.
#### YAML source
```yaml
- from:
    uri: 'netty-http:http://0.0.0.0:8080:'
    steps:
    - to:
        uri: sql:select * from actor
        parameters:
          dataSource: '#dataSource'
    - marshal:
        json:
          library: Jackson
- beans:
  - name: dataSource
    type: org.postgresql.ds.PGSimpleDataSource
    properties:
      serverName: 127.0.0.1
      portNumber: '5432'
      databaseName: dvdrental
      user: user
      password: password
  - name: someBean
    type: io.kaoto.test.backend.api.service.step.parser.camelroute.SomeBean
    properties:
      someProperty: someValue
      someObjectProperty:
        someObjectPropertyProperty: someObjectPropertyValue
```

#### Returned Kaoto JSON
```yaml
{
  "flows": [..snip..],
  "properties": {},
  "metadata": {
    "beans": [
      {
        "name": "dataSource",
        "type": "org.postgresql.ds.PGSimpleDataSource",
        "properties": {
          "serverName": "127.0.0.1",
          "portNumber": "5432",
          "databaseName": "dvdrental",
          "user": "user",
          "password": "password"
        }
      },
      {
        "name": "someBean",
        "type": "io.kaoto.test.backend.api.service.step.parser.camelroute.SomeBean",
        "properties": {
          "someProperty": "someValue",
          "someObjectProperty": {
            "someObjectPropertyProperty": "someObjectPropertyValue"
          }
        }
      }
    ]
  }
}
```

 This issue is to just support the source code. UI for bean configuration has to be addressed in a separate issue (#1722). At this point the frontend needs to keep the beans in the background without rendering anything on the canvas, and use it only when it talks to the backend.

Note that the type of `/beans/properties` is `object`. It has to allow arbitrary properties including object, for example
```yaml
- beans:
  - name: exampleBean
    type: org.example.some.Type
    properties:
      someProp: var
      someObject:
        some3rdObject:
          some3rdPbojectProp: foo
```
