### ISSUE TITLE
Bean configuration UI

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1722]
### Please describe the feature that you want to propose

While `beans` support at source code level is to be added soon https://github.com/KaotoIO/kaoto-ui/issues/1721
We also need to design how to let users configure those `beans` in Kaoto. Since `beans` is not a part of the flow, we need a separate view for configuring it apart from the flow graph as a tree of steps. We start from `beans`, but there're other type of "out of the flow" objects that could be defined in the Camel Route, such as `error-handler` and `on-exception`.

#### Camel Route
- beans
- error-handler
- on-exception
- routes
- camel-context
- ...
#### Kamelet
- `/spec/template/beans`
#### Integration
- `/spec/flows/beans`
---

Related issue about adding contextual endpoint for specific DSLs: https://github.com/KaotoIO/kaoto-backend/issues/657

**Comment by igarashitm** [comment]
#### Schema: Camel Route Beans
```json
      {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "properties" : {
            "type" : "object"
          },
          "type" : {
            "type" : "string"
          }
        },
        "required" : [ "name", "type" ]
      }
```

#### Schema: Kamelet Beans
Still looking for the schema, it has different structure for properties, for example - https://github.com/apache/camel-kamelets/blob/main/kamelets/mysql-sink.kamelet.yaml#L98-L104
```yaml
      - name: dsBean
        type: "#class:org.apache.commons.dbcp2.BasicDataSource"
        property:
          - key: username
            value: '{{username}}'
          - key: password
            value: '{{password}}'
```
`vavlue` here seems to be `string`
