### ISSUE TITLE
nginx configuration doesn't allow to send long routes

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#2004]
### Describe the Bug

Using https://red.ht/kaoto-snapshot, `nginx` is returning an error for long routes.

### Steps to Reproduce the Bug or Issue

1. Go to https://red.ht/kaoto-snapshot (it should be possible to reproduce it locally by running the docker image)
2. Paste the following Rest DSL routes

<details>
  <summary>Rest DSL routes</summary>

```yaml
- rest:
    path: /api/v1/
    description: API Legacy version - [deprecated]
    post:
    - uri: /pet
      to:
        uri: direct:addPet
    - uri: /pet/{petId}
      to:
        uri: direct:updatePetWithForm
    - uri: /pet/{petId}/uploadImage
      to:
        uri: direct:uploadFile
    - uri: /store/order
      to:
        uri: direct:placeOrder
    - uri: /user
      to:
        uri: direct:createUser
    - uri: /user/createWithList
      to:
        uri: direct:createUsersWithListInput
    get:
    - uri: /pet/findByStatus
      to:
        uri: direct:findPetsByStatus
    - produces: application/json
      uri: /pet/findByTags
      to:
        uri: direct:findPetsByTags
    - produces: application/json
      uri: /pet/{petId}
      to:
        uri: direct:getPetById
    - uri: /store/inventory
      to:
        uri: direct:getInventory
    - uri: /store/order/{orderId}
      to:
        uri: direct:getOrderById
    - uri: /user/login
      to:
        uri: direct:loginUser
    - uri: /user/logout
      to:
        uri: direct:logoutUser
    - uri: /user/{username}
      to:
        uri: direct:getUserByName
    delete:
    - uri: /pet/{petId}
      to:
        uri: direct:deletePet
    - uri: /store/order/{orderId}
      to:
        uri: direct:deleteOrder
    - uri: /user/{username}
      to:
        uri: direct:deleteUser
    put:
    - uri: /pet
      to:
        uri: direct:updatePet
    - uri: /user/{username}
      to:
        uri: direct:updateUser
- rest:
    path: /api/v2/
    description: API 2.0 version - [deprecated]
    get:
    - uri: /pet/findByStatus
      to:
        uri: direct:findPetsByStatus
    - produces: application/json
      uri: /pet/findByTags
      to:
        uri: direct:findPetsByTags
    - produces: application/json
      uri: /pet/{petId}
      to:
        uri: direct:getPetById
    - uri: /store/inventory
      to:
        uri: direct:getInventory
    - uri: /store/order/{orderId}
      to:
        uri: direct:getOrderById
    - uri: /user/login
      to:
        uri: direct:loginUser
    - uri: /user/logout
      to:
        uri: direct:logoutUser
    - uri: /user/{username}
      to:
        uri: direct:getUserByName
    put:
    - uri: /pet
      to:
        uri: direct:updatePet
    - uri: /user/{username}
      to:
        uri: direct:updateUser
- rest:
    path: /api/v3/
    description: API stable version
    get:
    - uri: /pet/findByStatus
      to:
        uri: direct:findPetsByStatus
    - produces: application/json
      uri: /pet/findByTags
      to:
        uri: direct:findPetsByTags
    - produces: application/json
      uri: /pet/{petId}
      to:
        uri: direct:getPetById
    - uri: /store/inventory
      to:
        uri: direct:getInventory
    - uri: /store/order/{orderId}
      to:
        uri: direct:getOrderById
    - uri: /user/login
      to:
        uri: direct:loginUser
    - uri: /user/logout
      to:
        uri: direct:logoutUser
    - uri: /user/{username}
      to:
        uri: direct:getUserByName
    put:
    - uri: /pet
      to:
        uri: direct:updatePet
    - uri: /user/{username}
      to:
        uri: direct:updateUser
- rest:
    path: /api/v4/
    description: API experimental version
    get:
    - uri: /pet/findByStatus
      to:
        uri: direct:findPetsByStatus
    - produces: application/json
      uri: /pet/findByTags
      to:
        uri: direct:findPetsByTags
    - produces: application/json
      uri: /pet/{petId}
      to:
        uri: direct:getPetById
    - uri: /store/inventory
      to:
        uri: direct:getInventory
    - uri: /store/order/{orderId}
      to:
        uri: direct:getOrderById
    - uri: /user/login
      to:
        uri: direct:loginUser
    - uri: /user/logout
      to:
        uri: direct:logoutUser
    - uri: /user/{username}
      to:
        uri: direct:getUserByName
    put:
    - uri: /pet
      to:
        uri: direct:updatePet
    - uri: /user/{username}
      to:
        uri: direct:updateUser
```
</details>

3. Click on `sync code`
4. Notice that the route is replaced with the error payload from `nginx`

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/98622ca4-cd65-4a20-a87a-d1e831a859e5)

### Platform

- OS: [macOS, Windows, Linux]
- Browser: [Firefox]
- Version: [snapshot]
