### ISSUE TITLE
Can't add new KameletBinding route using the code editor in multiroute setup

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2057]
### Describe the Bug
Users can't add new KameletBinding using the code editor - e.g. appending following KameletBinding and syncing doesn't create new route in the canvas:

```
---
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: KameletBinding16878663834731687866383473
spec:
  source: null
  sink: null
```

### Steps to Reproduce the Bug or Issue

1. add the above mentioned KameletBinding
2. sync code changes
3. see no KameletBinding was added to the canvas

### Screenshots or Videos

![Peek 2023-06-27 13-46](https://github.com/KaotoIO/kaoto-ui/assets/4180208/b3a1de5f-b611-4e29-88ce-549a4d020ffc)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]
