### ISSUE TITLE
Content erased when opening google-bigquery-sink.kamelet.yaml

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#2120]
### Describe the Bug

When opening https://github.com/apache/camel-kamelets/blob/main/kamelets/google-bigquery-sink.kamelet.yaml , the content of the file is erased.
In console log:
```
TypeError: _a[0] is undefined
    handleChanges SourceCodeEditor.tsx:67
    promise callback*handleChanges SourceCodeEditor.tsx:66
    updateModelFromTheEditor SourceCodeEditor.tsx:118
    onCustomClick CodeEditorControl.js:32
```

### Steps to Reproduce the Bug or Issue

with red.ht/kaoto-snapshots:
1. Open source code editor
2. Paste content https://raw.githubusercontent.com/apache/camel-kamelets/main/kamelets/google-bigquery-sink.kamelet.yaml
3. Click on sync
--> the canvas remains empty

with latest main branches in VS Code:
1. Rightc-ick on the file https://raw.githubusercontent.com/apache/camel-kamelets/main/kamelets/google-bigquery-sink.kamelet.yaml -- >Open with Kaoto graphical editor
2. the canvas is empty and the content of the wile is empty

### Platform

red.ht/kaoto-snapshot

**Comment by apupier** [comment]
same behavior with https://github.com/apache/camel-k-examples/blob/main/kamelets/aws-s3-to-kafka-with-timestamp-router/log-sink.kamelet.yaml

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: log-sink
  annotations:
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNDAgMjQwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSIuNjY3IiB4Mj0iLjQxNyIgeTE9Ii4xNjciIHkyPSIuNzUiPjxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iIzM3YWVlMiIvPjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iIzFlOTZjOCIvPjwvbGluZWFyR3JhZGllbnQ+PGxpbmVhckdyYWRpZW50IGlkPSJiIiB4MT0iLjY2IiB4Mj0iLjg1MSIgeTE9Ii40MzciIHkyPSIuODAyIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiNlZmY3ZmMiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNmZmYiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48Y2lyY2xlIGN4PSIxMjAiIGN5PSIxMjAiIHI9IjEyMCIgZmlsbD0idXJsKCNhKSIvPjxwYXRoIGZpbGw9IiNjOGRhZWEiIGQ9Ik05OCAxNzVjLTMuODg4IDAtMy4yMjctMS40NjgtNC41NjgtNS4xN0w4MiAxMzIuMjA3IDE3MCA4MCIvPjxwYXRoIGZpbGw9IiNhOWM5ZGQiIGQ9Ik05OCAxNzVjMyAwIDQuMzI1LTEuMzcyIDYtM2wxNi0xNS41NTgtMTkuOTU4LTEyLjAzNSIvPjxwYXRoIGZpbGw9InVybCgjYikiIGQ9Ik0xMDAuMDQgMTQ0LjQxbDQ4LjM2IDM1LjcyOWM1LjUxOSAzLjA0NSA5LjUwMSAxLjQ2OCAxMC44NzYtNS4xMjNsMTkuNjg1LTkyLjc2M2MyLjAxNS04LjA4LTMuMDgtMTEuNzQ2LTguMzYtOS4zNDlsLTExNS41OSA0NC41NzFjLTcuODkgMy4xNjUtNy44NDMgNy41NjctMS40MzggOS41MjhsMjkuNjYzIDkuMjU5IDY4LjY3My00My4zMjVjMy4yNDItMS45NjYgNi4yMTgtLjkxIDMuNzc2IDEuMjU4Ii8+PC9zdmc+"
    camel.apache.org/provider: "Apache Software Foundation"
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.group: "Log"
spec:
  definition:
    title: "Log Sink"
    description: |-
      Log something
    type: object
  flow:
    from:
      uri: "kamelet:source"
      steps:
      - to:
          uri: "log:info?showAll=true"
```
