### ISSUE TITLE
Uploading a yaml file does not update the diagram

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#828]
### Describe the Bug

The diagram is not updated when uploading a yaml file

### Steps to Reproduce the Bug or Issue

- Open Kaoto UI
- Open Source code panel
- Click on Upload button
- upload file with this content for instance:

```
  apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: willItKeepThisName
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: webhook-source
      kind: Kamelet
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: avro-deserialize-action
      kind: Kamelet
```
--> the diagram stays empty (with "add a step")

### Screenshots or Videos

![uploadingNotWorking](https://user-images.githubusercontent.com/1105127/196175010-7920fe74-b363-454d-868b-715df1ee1074.gif)

### Platform

- OS: Fedora 36
- Browser: Chrome
- Version: commit b07fe3e1404bd19e068e76092477b859142fa9cc
