### ISSUE TITLE
[branches] NextStep is undefined when branches don't have a following step

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#870]
### Describe the Bug

Adding a step with branches without a following step throws an error that makes the frontend a blank page:

```
Uncaught TypeError: nextStep is undefined
    buildBranchSpecialEdges visualizationService.ts:80
    buildBranchSpecialEdges visualizationService.ts:47
    buildNodesAndEdges Visualization.tsx:59
    Visualization Visualization.tsx:42
    React 12
[visualizationService.ts:80:41](webpack://kaoto-ui/src/services/visualizationService.ts?bd2c)
    buildBranchSpecialEdges visualizationService.ts:80
    forEach self-hosted:208
    buildBranchSpecialEdges visualizationService.ts:47
    buildNodesAndEdges Visualization.tsx:59
    Visualization Visualization.tsx:42
    React 10
    performSyncWorkOnRoot self-hosted:1231
```

### Steps to Reproduce the Bug or Issue

1. Enter Kaoto
2. On Settings, select the `Camel Route` type of DSL
3. Add a first step, any, like `timer`
4. Add a second step with branches, like `choice`
5. Add on the source code editor a branch to the previous step, like:

```
- choice:
          when:
          - simple: '{{?foo}}'
            steps:
            - dynamic-router:
                expression:
                  simple: ${body}
```

### Screenshots or Videos

https://user-images.githubusercontent.com/726590/198994161-8ca2b906-a464-4574-acb4-6a3eaef953d8.mp4

### Platform

- OS: Linux
- Browser: Firefox
- Version: `main`
