### ISSUE TITLE
[branches] Location of branches 

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#871]
### Describe the Bug

Branches steps are floating somewhere they shouldn't.

### Steps to Reproduce the Bug or Issue

1. Open Kaoto
2. In Settings, select `Camel Route`
3. [Optional] Add first step `timer`
4. [Optional] Add last step `log`
5. [Optional] Add intermediate step `choice`
6. In the source code editor, complete the route with this:
```
- from:
    uri: timer:null
    steps:
    - choice:
        when:
        - simple: '{{?foo}}'
          steps:
          - dynamic-router:
              expression:
                simple: ${body}
    - to:
        uri: log:null
```

### Screenshots or Videos

Firefox:
![imagen](https://user-images.githubusercontent.com/726590/198995080-7268be30-2c08-409c-ad02-81e249f56721.png)

Chromium:
![imagen](https://user-images.githubusercontent.com/726590/198995269-b6523272-a476-42f5-9e79-343863ac3931.png)

### Platform

- OS: Linux
- Browser: Chrome and Firefox
- Version: Latest `main`
