### ISSUE TITLE
Visualization: Camel routes aren't being rendered

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#958]
### Describe the Bug

Camel routes are not being show in the Visualization, even if you select the correct DSL beforehand. There is also an error in the browser console:

```
Cannot read properties of null (reading 'name')
    at eval (SourceCodeEditor.tsx?11c6:38:1)
```

### Steps to Reproduce the Bug or Issue

1. Go to Settings
2. Change DSL to Camel Route
3. Click save
4. Open the Source Code Editor
5. Paste a Camel route YAML
6. See it doesn't render the route in the Visualization

You can try with one of these YAMLs:

```yaml
- from:
    uri: "timer:start"
    steps:
    - choice:
        precondition: true
        when:
        - simple: "{{?red}}"
          steps:
          - to: "log:red"
        - simple: "{{?blue}}"
          steps:
          - to: "log:blue"
        otherwise:
          steps:
          - to: "log:info"
```

```yaml
- from:
    uri: "direct:start"
    steps:
    - set-property:
        name: test
        expression:
          simple: "${body}"
    - to: "mock:result"
```

```yaml
- from:
    uri: "direct:route"
    steps:
    - filter:
        simple: "${body.startsWith(\\"a\\")}"
        steps:
          - to: "mock:filter"
    - to: "mock:route"
```

### Screenshots or Videos

![Screen Shot 2022-11-22 at 12 38 27 pm](https://user-images.githubusercontent.com/3844502/203316039-7262c9fe-17b2-4ac0-8f8e-2ea9bd3efec3.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.5.0-dev
