### ISSUE TITLE
Visualization: Issues with certain types of branching

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#960]
### Describe the Bug

NOTE: Give this issue a better name. :)

There are a few issues with certain types of branching:
- `chunk` step is disconnected
- Pressing the `+` button after the `idempotent` step (to add another step) adds it after `chunk`
- `load-balancer` branches are not being used (i.e. branch branches)

### Steps to Reproduce the Bug or Issue

1. Go to Settings
2. Change DSL to `Kamelet`
3. Save and close
4. Open the Source Code Editor
5. Add the YAML below
6. See issue in the Visualization
7. Next issue: Press the + button after `idempotent` step
8. Choose another step
9. See that it gets added after the `chunk` step

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.support.level: Preview
    camel.apache.org/catalog.version: main-SNAPSHOT
    camel.apache.org/kamelet.icon: whatever
    camel.apache.org/provider: Apache Software Foundation
    camel.apache.org/kamelet.group: Kaoto
  labels:
    camel.apache.org/kamelet.type: sink
  name: eip-action-sink
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
    - camel:core
    - camel:kamelet
    - camel:bean
    - camel:aws2-eventbridge
    - camel:chunk
  template:
    from:
      uri: kamelet:source
      steps:
        - choice:
            when:
              - simple: "{{?baz}}"
                steps:
                  - load-balance:
                      weighted:
                        distribution-ratio: 2,1
                        round-robin: false
                      steps:
                        - log:
                            message: test
                            logging-level: INFO
                            log-name: yaml
            otherwise:
              steps:
                - remove-header:
                    name: removeme
        - filter:
            simple: "{{?foo}}"
            steps:
              - set-body:
                  simple: abc
              - idempotent-consumer:
                  idempotent-repository: myRepo
                  simple: ${header.id}
                  steps:
                    - set-body:
                        simple: cheesecubez
        - to:
            uri: aws2-eventbridge
        - to:
            uri: chunk:null
```

### Screenshots or Videos

![Screen Shot 2022-11-22 at 1 48 17 pm](https://user-images.githubusercontent.com/3844502/203333356-f54565e7-94e8-4b06-8da8-3d1c1625f4e6.png)

### Platform

- OS: macOS, Debian
- Browser: Chrome, Firefox
- Version: 0.5.0-dev
